api-docs:
  server:
    mall-service: http://localhost:8082
    user-manager: http://localhost:8001
  oauth2:
    authorization-url: http://localhost:8081/oauth2/authorize
    token-url: http://localhost:8081/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      use-basic-authentication-with-access-code-grant: true